### ISSUE TITLE
client.Payments.CreateCreditCard returning null in production

### ISSUE THREAD

**Issue by RodrigoQuintas** [wirecardBrasil/moip-sdk-dotnet#11]
Hello Guys,
When I call the method client.Payments.CreateCreditCard to create a payment is returning null, using in sandbox work fine, but in production return null.

Anyone else with this problem?
:(

**Comment by matmiranda** [comment]
@RodrigoQuintas  and @kroghot,

Try this [Wirecard ](https://github.com/matmiranda/WirecardCSharp) library!

Thank you 😄

**Comment by somentelucas** [comment]
Please use this [SDK](https://github.com/matmiranda/MoipCSharp) instead.
