### ISSUE TITLE
New Client

### ISSUE THREAD

**Issue by lGuzl** [wirecardBrasil/moip-sdk-dotnet#30]
Bom dia,

Estou tentando usar este sdk, porém estou com o seguinte problema.

Criei a conta no moip, e criei a mesma em sandbox.

Tenho o token e chave do sandbox, porém percebi que na criação do client, ele solicita o oAuth.

No caso, recorri aos links de pessoas daqui que já tiveram o mesmo problema, porém os links de ajuda estão obsoletos.

Como devo proceder? Já utilizei outros sdk fazendo conexão com token/key e consigo utilizar corretamente, porém nenhuma delas funciona no ios, onde preciso.

**Comment by matmiranda** [comment]
Não entendi muito bem, o seu problema está no link de ajuda ?

**Comment by matmiranda** [comment]
Se não é suportado para xamarin forms ou xamarin native, use [HttpClient](https://docs.microsoft.com/pt-br/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client).

**Comment by lGuzl** [comment]
Ok Matheus, obrigado pela ajuda de qualquer forma, acabei encontrando outra biblioteca que me ajudou.

No entanto, fica a dica sobre o oAuth, talvez outras pessoas precisem de ajuda.

Abs.

**Comment by matmiranda** [comment]
#31

**Comment by matmiranda** [comment]
#30

**Comment by mbppower** [comment]
Acho que o problema é que a API 2.0 aceita autenticação usando "Basic" no "Authorization" header, porém essa lib sempre força o "Bearer".


```

Moip.Utilities.APIHelper.GetHeader();

_headers.Add("Authorization", string.Format("Bearer {0}", Configuration.OAuthAccessToken));
```

**Comment by matmiranda** [comment]
@lGuzl veja essa biblioteca: https://github.com/matmiranda/MoipCSharp

**Comment by somentelucas** [comment]
Please use this [SDK](https://github.com/matmiranda/MoipCSharp) instead.
