### ISSUE TITLE
Support NetStandard

### ISSUE THREAD

**Issue by brunoportess** [wirecardBrasil/moip-sdk-dotnet#36]
Quero implementar o gateway de vocês, mas vocês ainda estão com suporte apenas para .net 4.5, isso mesmo?
Uso .net core e app em xamarin, porque não migraram pra NetStandard todos esses anos ?

**Comment by RodrigoQuintas** [comment]
Tenho a mesma dúvida, estou migrando minha WEB API para .net core.

**Comment by matmiranda** [comment]
@brunoportess agora é essa: https://github.com/matmiranda/WirecardCSharp

**Comment by somentelucas** [comment]
Excelente trabalho, @matmiranda! A partir de agora o Readme dessa SDK redireciona para a sua SDK, ao longo desse mês também iremos alterar nossa documentação oficial com os métodos da sua SDK. Parabéns mais uma vez pelo trabalho ❤️Contribuição f***!
